#!/bin/bash

#  git remote add dep-mruby https://github.com/mruby/mruby.git
#  git remote add dep-mruby-test https://github.com/mruby/mruby.git

git subtree pull --prefix=mruby --squash dep-mruby master
git subtree pull --prefix=mruby_test --squash dep-mruby-test master
