#!/bin/sh

#  git remote add dep-mruby https://github.com/mruby/mruby.git

REMOTE_REPO_NAME=dep-ngx_devel_kit
REMOTE_REPO_URL=https://github.com/simplresty/ngx_devel_kit.git
SUBTREE_DIR=dependence/ngx_devel_kit

git remote | grep ${REMOTE_REPO_NAME} > /dev/null
if [ $? -ne 0 ]; then
  echo "Missing remote repository ${REMOTE_REPO_NAME}"
  echo -n "Do you want to add (y/n)? "
  read answer
  if [ X$answer == "Xy" -o X$answer == "XY" ]; then
    git remote add ${REMOTE_REPO_NAME} ${REMOTE_REPO_URL}
    echo "Added ${REMOTE_REPO_URL} as ${REMOTE_REPO_NAME}."
  else
    echo "Aborted."
    exit 1
  fi
fi

git subtree pull --prefix=${SUBTREE_DIR} --squash ${REMOTE_REPO_NAME}  master

exit 0
