#!/bin/sh

REMOTE_REPO_NAME=dep-ngx_devel_kit
REMOTE_REPO_URL=https://github.com/vision5/ngx_devel_kit.git
SUBTREE_DIR=dependence/ngx_devel_kit
REF=master

git remote | grep ${REMOTE_REPO_NAME} > /dev/null
if [ $? -ne 0 ]; then
  echo "Missing remote repository ${REMOTE_REPO_NAME}"
  echo -n "Do you want to add (y/n)? "
  read answer
  if [ X$answer = "Xy" -o X$answer = "XY" ]; then
    git remote add ${REMOTE_REPO_NAME} ${REMOTE_REPO_URL}
    echo "Added ${REMOTE_REPO_URL} as ${REMOTE_REPO_NAME}."
  else
    echo "Aborted."
    exit 1
  fi
fi
if [ $# -eq 1 ]; then
  if [ $1 = "-h" -o $1 = "--help" ]; then
    echo "Usage: `basename $0` [ref]"
    echo "       'ref' can be a SHA-1 hash, tag or branch. The default ref is 'master'."
    exit 0
  else
    REF=$1
  fi
fi

git subtree pull --prefix=${SUBTREE_DIR} --squash ${REMOTE_REPO_NAME} ${REF}

exit 0
